# Lab Week 4
In this lab, we experiment how KNN works.

### Dataset
Let's considet the Titanic dataset available on:
https://github.com/andvise/DataAnalyticsDatasets/blob/main/titanic.csv

In [ ]:
import pandas as pd
df = pd.read_csv("https://github.com/andvise/DataAnalyticsDatasets/blob/dc74027bd063510ede437e4d612f41eb078e49b9/titanic.csv?raw=true")
df.dtypes

PassengerId                  int64
Survived                     int64
Pclass                       int64
Name                        object
Sex                         object
Age                        float64
Siblings/Spouses Aboard      int64
Parents/Children Aboard    float64
Fare                       float64
dtype: object

Replace the missing values with 0.

In [ ]:
df = df.fillna(0)

The goal is to predict if you would have survived the Titanic accident.

Create a Pandas Series containing your personal data (feel free to use random values).

In [ ]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age',
       'Siblings/Spouses Aboard', 'Parents/Children Aboard', 'Fare'],
      dtype='object')

In [ ]:

my_data = pd.Series([999, 1, 2, 'Andrea', 'male', 18, 1, 0, 25], index= ['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age',
       'Siblings/Spouses Aboard', 'Parents/Children Aboard', 'Fare'])

In [ ]:
col_relevant = [ 'Pclass', 'Age', 'Siblings/Spouses Aboard', 'Parents/Children Aboard', 'Fare']

df_diff = df[col_relevant] - my_data[col_relevant]

In [ ]:
df_diff = abs(df_diff)
distances = df_diff.sum(axis=1).sort_values()
k = 7
distances.head(k).index

Index([543, 424, 648, 787, 135, 421, 314], dtype='int64')

In [ ]:
df.iloc[distances.head(k).index, 1].mode()

0    1
Name: Survived, dtype: int64

To classify yourself consider your closest neighbour according to the numerical columns. Which columns should you consider?

In [ ]:
df.sort_values(by='Age')

## YOUR CODE HERE

,PassengerId,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
799,800,1,3,Master. Assad Alexander Thomas,male,0.42,0,1.0,8.5167
751,752,1,2,Master. Viljo Hamalainen,male,0.67,1,1.0,14.5000
641,642,1,3,Miss. Eugenie Baclini,female,0.75,2,1.0,19.2583
466,467,1,3,Miss. Helene Barbara Baclini,female,0.75,2,1.0,19.2583
77,78,1,2,Master. Alden Gates Caldwell,male,0.83,0,2.0,29.0000
...,...,...,...,...,...,...,...,...,...
115,116,0,3,Mr. Patrick Connors,male,70.50,0,0.0,7.7500
490,491,0,1,Mr. Ramon Artagaveytia,male,71.00,0,0.0,49.5042
95,96,0,1,Mr. George B Goldschmidt,male,71.00,0,0.0,34.6542
847,848,0,3,Mr. Johan Svensson,male,74.00,0,0.0,7.7750
627,628,1,1,Mr. Algernon Henry Wilson Barkworth,male,80.00,0,0.0,30.0000

Subtract the selected columns from the dataframe.

In [ ]:
df.sample(1).index

Index([829], dtype='int64')

Find which index has the closest Manhattan Distance.

In [ ]:
## YOUR CODE HERE

Check if the person on that index survived or not.

In [ ]:
## YOUR CODE HERE